sudo: false
language: node_js
addons:
  code_climate:
    repo_token:
      secure: cctSyhxkbNc60x4WzdF9J3I0HZUQ674i0Cilo2kA8D7Lz9m66S/Jujkl3tJso5kO2RHJT0KdeqIjn+3JcuBUhY+sRg8Xu1vMt++r8RqR1+L5IXUXIlipr6ENsiQL+d9C11uaGzE5ZFvlMOIPvvxSgjx2ier2bn5pEPuxIMh7Az8=
after_script:
  - find .
  - cat ./coverage/lcov.info | codeclimate
deploy:
  provider: npm
  email: BangorDevelopment@thebookpeople.co.uk
  api_key:
    secure: GEN8BDwoT63MiY692GnKIXKKGaLk8JvTfUIcG7zNARwo8X2jVsk67IOd4P28WDjedTbRZXAkGXRW5RSkP4MS/OMUbYF2e/Kau+U+BsvawLG5IAI2qW0Sf7szehY8duEYZJKcMtSywcoNZ+/fr1GI/WrjyDj7hElu4CFt2tsIBjk=
  on:
    tags: true
